#!/usr/bin/env bash
"""the default server listens on port 80 for a request which is a proxy locoalhost on  port 5003"""

server {
    listen 80 default_server;
    listen [::]:80 default_server;

    server_name 54.210.147.220;

    location / {
        proxy_pass http://0.0.0.0:5003/web_dynamic/2-hbnb.py/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /static/ {
        alias /home/ubuntu/AirBnB_clone_v4/web_dynamic/static/;
    }

    location /scripts/ {
        alias /home/ubuntu/AirBnB_clone_v4/web_dynamic/static/scripts/;
    }

    error_page 404 /404.html;
    location = /404.html {
        root /usr/share/nginx/html;
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
